### ISSUE TITLE
GetCaseSchema Filter for cases that cannot opened anymore

### ISSUE THREAD

**Issue by Marow** [OPSkins/trade-opskins-api#103]
Can you please add a filter or something that i can say, i want only cases which can be opened...
for GetCaseSchema?

I dont want case 3 in that, cause that cannot opened anymore

**Comment by QuantumLlama** [comment]
Hello,

Will submit your proposal to our team.

Meanwhile, you may check `remaining_opens` property, which will be `0` if the case has been disabled.

Thanks
