### ISSUE TITLE
Check if trade url is valid?

### ISSUE THREAD

**Issue by harisvreto** [OPSkins/trade-opskins-api#105]
Hello everyone,
Is there any way to check whether the trade url is valid and if exist, except the way where you need to fake an offer. How do you actually check it on trade.opskins.com?
I think you should add this feature.

Thank you in advance

**Comment by QuantumLlama** [comment]
Hello,

Do you mean on the UI or API?

**Comment by tuz1k** [comment]
He means API @QuantumLlama

**Comment by Kevin-Reinke** [comment]
Get the user's inventory and if it fails then the user is most likely non existent.
