### ISSUE TITLE
Multiple appids on getinventory endpoint?

### ISSUE THREAD

**Issue by AlaDyn172** [OPSkins/trade-opskins-api#108]
Hello,

Can the developer make something on getinventory endpoints, so you can set multiple appids?
The order of response items will be order of appids...
GetInventory({
app_id: [1,2,3,4,5]
});
will have a response of items... first of appid 1, then 2, then 3.. and so on.

Could it be made? It will be easiear for websites who has multiple appids in one inventory.

**Comment by gabenthegamer** [comment]
+1

**Comment by makcc666** [comment]
+1

**Comment by luukonetap** [comment]
Any updates on this? Last time I checked, when looping through appids like VGO, Shoes, Apparel and all the other vIRL appids making so many requests to the API, I've had cloudflare block my request.
Has anyone else had cloudflare blocking requests or is this not an issue?

**Comment by feed4rz** [comment]
@luukonetap you can workaround that with inventory loading be done in frontend, because the endpoint doesnt require apikey.
