### ISSUE TITLE
why there's no sandbox for opskins?

### ISSUE THREAD

**Issue by Nisthar** [OPSkins/trade-opskins-api#109]
As a developer, its very difficult to work with opskins without a sandbox. 

You need to buy real keys to for each test. 

Why is opskins not make a sandbox api for sendKeyRequest API?

**Comment by AlaDyn172** [comment]
You can make a test object with the caseopened result instead of the `request` URL of an actual case opening until they add sandbox.

**Comment by ha1331** [comment]
@AlaDyn172  what makes you think there's going to be a sandbox in the first place?

**Comment by CollinHerber** [comment]
PLEASE make a sandbox environment!

**Comment by Nisthar** [comment]
@QuantumLlama Any estimate on when this will be available?
