### ISSUE TITLE
user id and user object

### ISSUE THREAD

**Issue by atmd83** [OPSkins/trade-opskins-api#11]
when we get a user object, something like:

```
{
 "uid": 4876629,
  "steam_id": "76561198137570052",
  "display_name": "K4g0w1",
  "avatar": "https://steamcdn-a.opskins.media/steamcommunity/public/images/avatars/a5/a554740fc40a2e142baa57ddaebb977363a27f97.jpg"
}
```

when steam ban the bots, will the user object keep the same structure?
I presume (but could of course be wrong) that most people wont use steam login and will use opskins login / email/password. will that change the user contract?

**Comment by rannmann** [comment]
Sender and recipient details on trade offers will not change after the OPSkins Steam bots are gone.  You don't need a SteamID to use OPSkins right now, and in the case that the user does not have a SteamID associated with their account, that value will be an empty string.

The avatar should default to a placeholder image for now in the event that we don't have Steam information about them.
