### ISSUE TITLE
IItem/GetItems/v1?sku_filter no response for some id's

### ISSUE THREAD

**Issue by David373** [OPSkins/trade-opskins-api#114]
Following can be found in Hyperbeast Case outcomes - 

`https://api-trade.opskins.com/ICase/GetCaseOdds/v1`
```
{"sku":6294,"weight":"205116","relative_weight":"0.00004775729232","relative_percent":"0.00477572923163"},
{"sku":6295,"weight":"153837","relative_weight":"0.00003581796924","relative_percent":"0.00358179692372"}
```

However, once I try to pull them with `https://api-trade.opskins.com/IItem/GetItems/v1?sku_filter=6294`

I get no response, there are plenty more of those ID's, if needed can find them.

`{"status":1,"time":1545438469,"response":{"items":[]}}`

**Comment by AlaDyn172** [comment]
Hello,

The `IItem/GetItems` is for VGO-only items.
For vIRL you should use `https://api-trade.opskins.com/IItem/GetAllItems/v1` along with `app_id` parameter.

**Comment by David373** [comment]
How come it works for like 95% other items?
