### ISSUE TITLE
WAX Stickers - Item/Return Count: Don't show items in active trades

### ISSUE THREAD

**Issue by Kevin-Reinke** [OPSkins/trade-opskins-api#115]
As shown in the screenshots below, when I check "Don't show items in active trades" the count changes to 1 while 6 skins remain shown (the count shouldn't change - 6).

![screenshot 296](https://user-images.githubusercontent.com/15372635/50371844-798c5d80-0577-11e9-9ef2-4c7dc75bf283.png)
![screenshot 297](https://user-images.githubusercontent.com/15372635/50371845-7c874e00-0577-11e9-8b7d-cce3bead6c42.png)

**Comment by QuantumLlama** [comment]
Hello,

This should be fixed now.

Thanks!
