### ISSUE TITLE
case opening offer auto-accepted?

### ISSUE THREAD

**Issue by jor112358** [OPSkins/trade-opskins-api#119]
I just make a SendKeyRequest, without doing any operations (calling AcceptOffer or clicking Accept on opskins.com), and two factor code was always enabled,  soon I got a message said "Someone sent you an offer and it was auto-accepted".

**Comment by QuantumLlama** [comment]
Hello,

This is normal behavior for case-opening offers.  This feature was introduced some time ago.

Added a new bullet explaining this [here](https://github.com/OPSkins/trade-opskins-api/blob/master/ICaseSite/SendKeyRequest.md).

Thanks
