### ISSUE TITLE
Wrong response in GetItemsDefinitions

### ISSUE THREAD

**Issue by lelek16** [OPSkins/trade-opskins-api#124]
Hi, docs say that attributes property in GetItemDefinitions (https://github.com/OPSkins/trade-opskins-api/blob/master/IItem/GetItemDefinitions.md) is object, but not always.

Example:
```
{  
            "def_id":2346,
            "sku":null,
            "internal_app_id":14,
            "name":"Drax The Wrecker's Graffiti",
            "market_name":"WAX Digital Art | Drax The Wrecker\\'s Graffiti",
            "color":"FFF",
            "image":"https://static.wax.io/d-img/dynamic-apps/img/6b721043e14bf0b9e2e24c1a909df3f6.png",
            "suggested_price":null,
            "suggested_price_floor":null,
            "attributes":[  

            ]
 },
```

I saw there few more similar cases, do you need them?

**Comment by exogenesick** [comment]
:+1: 

It looks like only 15 out of 21 apps has consistent data model. This situation cause that there is no option to be fully integrated through Express Trade API with every app.
