### ISSUE TITLE
Invalid data in GetOffers response

### ISSUE THREAD

**Issue by memiamap** [OPSkins/trade-opskins-api#127]
When executing `/ITrade/GetOffers/v1/`, _occasionally_ the JSON that is returned doesn't match the definition.

According to the site docs, the response should contain an `offers` array-object which is an _Array of Standard Trade Offer Object_.

However, sometimes there are boolean values in the array, so it appears like:

```

[{TradeOfferObject},{TradeOfferObject},false,{TradeOfferObject}]
[false,{TradeOfferObject},{TradeOfferObject},{TradeOfferObject}]

```

What are the spurious booleans representing?  A subsequent call to `GetOffers` will not return the booleans.  They appear sporadically.

**Comment by lelek16** [comment]
I've noticed similar issues in different endpoints, where response doesn't match definition.
It looks like V1 works only with VGO.
Did you try V2 endpoint? They use it on their site.
