### ISSUE TITLE
How to get the trade token of the user I want to send a trade offer using the endpoint  ITrade/SendOffer

### ISSUE THREAD

**Issue by rohan-new** [OPSkins/trade-opskins-api#129]
I am unable to figure out on how to get a user's **trade token** so that I can use it in the **ITrade/SendOffer** API. I want to send a trade offer to a user whose trade url is not linked with his opskins account. 
The other alternative is using **ITrade/SendOfferToSteamId** but this requires a steamId as well which means linking the steam trade url

**Comment by henrikschwebcke** [comment]
For that you need a OAuth Token from the user with the scope "**identity_basic**".
Docs: [OAuth OPSkins](https://docs.opskins.com/public/en.html#oauth)
Then request his Trade URL with that token from [ITrade/GetTradeUrl](https://github.com/OPSkins/trade-opskins-api/blob/master/ITrade/GetTradeUrl.md).
