### ISSUE TITLE
IUser/GetInventory/v1 requires app_id

### ISSUE THREAD

**Issue by larsrusteberg** [OPSkins/trade-opskins-api#13]
# Description
IUser/GetInventory/v1 says that it doesn't require the app_id but the API requires it.

# API Response
```json
{
    "status": 400,
    "time": 1529496404,
    "message": "app_id input is required."
}
```

# Link
[https://github.com/OPSkins/trade-opskins-api/blob/master/IUser/GetInventory.md](https://github.com/OPSkins/trade-opskins-api/blob/master/IUser/GetInventory.md)

**Comment by rannmann** [comment]
Fixed in #15
