### ISSUE TITLE
IItem/GetItemsById not returning a default item object.

### ISSUE THREAD

**Issue by MordorKing78** [OPSkins/trade-opskins-api#14]
I've been trying to get the price of items using getItemsById but it doesn't seem to spit out the average price using this method which is stated that it does (this is using vgo items, not sure about other games).

This needs to be fixed.

**Comment by QuantumLlama** [comment]
A fix is in progress, will most likely be deployed today

**Comment by QuantumLlama** [comment]
A fix has been deployed. Added `unknown_items`, which contains an array of item ids that were not found in the database. It's now possible that `items` will be empty.
