### ISSUE TITLE
Help me with Google Authenticator. Pls

### ISSUE THREAD

**Issue by lonya** [OPSkins/trade-opskins-api#16]
how can I make Help me with Google Authenticator automatically generated. For a trade, twofactor_code is needed. I shake my head I can not do I will be happy with any help. sorry for my English 🔢

**Comment by QuantumLlama** [comment]
Hello,

Good question, API docs should probably be updated to contain this info.

You can use open-source libraries to generate two-factor codes and send it with your request.
One such library is https://github.com/speakeasyjs/speakeasy

You could also use an open-source SDK to consume the API requests, such as https://github.com/TheTimmaeh/node-expresstrade

These require a 2FA `secret`, you can get this secret code when you are enabling 2FA on [OPSkins.com account page](https://opskins.com/?loc=store_account#enable2fa). The API key and two-factor information is transferred automatically to ExpressTrade. So you can use the same API key & 2FA secret for accessing both OPSkins API & ExpressTrade API.

When you see the QR code, you should also see a Manual Code, save this in a safe place and use it as the `secret` for the libraries mentioned above. It looks something like **`Z29BPLS4LN1DJ7M5`** (delete spaces in-between). Don't forget to **finish your 2FA setup** on your mobile device to keep your account secure.

![image](https://user-images.githubusercontent.com/3676208/41814262-846dd7ce-7715-11e8-8817-2d6ab1e8927e.png)

**Comment by lonya** [comment]
Thank's man!!! You saved me. In general, I found a simple library for creating 2-factor-authentication code. All Easy and simple. I love you man. You directed to the right path! If someone comes in handy https://github.com/PHPGangsta/GoogleAuthenticator for PHP
