### ISSUE TITLE
Add case_id to /IItem/getItems

### ISSUE THREAD

**Issue by Kipcarry** [OPSkins/trade-opskins-api#17]
Hi,

I would like to see case_id to be added to /IItem/getItems. This way, you can easily fetch all the names, images etc. from the items from that case (so when there are multiple cases, you could only load the images from that case).

Regards,
Daan

**Comment by rannmann** [comment]
You can already do this by combining two API endpoints.

ICase/GetCaseSChema
  - takes `cases` int CSV input
  - Returns case image(s), name, id, and item **SKU**s that are in the case

IItem/GetItems
  - Takes `sku_filter` int CSV input, and wear_tier_index CSV input (ex: 1 for only factory new)
  - Returns item definitions, including name, images, rarity, etc.

**Comment by Kipcarry** [comment]
Wouldn't it be easier (especially when there will be a lot if cases) to directly implememt this feature?

**Comment by Nisthar** [comment]
@rannmann what do you do for non vgo cases? ICase/GetCaseSChema doesn't return def_id which is needed for IItem/GetAllItems
I can't use `IItem/GetItems` since it doesn't have sort option. It seems like opskins api need improvement.
