### ISSUE TITLE
Api response statuses

### ISSUE THREAD

**Issue by lwasak** [OPSkins/trade-opskins-api#19]
Hi,

Is there a list of status responses? For the _status_ field below?

`
{
    "status": 1,
    "time": 1528334546,
    "response": {
        "offer": {
            "some_data": "here"
        }
    }
}
`

I'm looking for a more normal way to detect that an item was already used in trade. Currently I receive such response:

`
{
    "status": 400,
    "time": 1530010378,
    "message": "There is an offer #XXXXXX with the same parameters."
}
`

Is status of 400 directly related with this case that item is already used? or does it mean something entirely different.

Can you point me in the right direction?

**Comment by rannmann** [comment]
If we haven't setup custom error codes for something yet, it uses the HTTP response code as the status.

Unfortunately that means for now you'll have to parse the message anytime the status isn't 1 in order to figure out what went wrong.

**Comment by ha1331** [comment]
@rannmann by parse you mean.... what? Is there a list of these possible `message`s ? So that I can parse something to connect it to a specific failure condition? If not, what am I supposed to parse and why? The only way I have been able to track these is, do stuff, do more stuff, something goes wrong and then you look at the message to figure out what's going on, but that is very tedious effort and you only catch the ones you are able to trigger. Now I guess I'm parsing the message, but it's not like parsing is the solution. The solution is to do your best to collect the possible failure condition and then prepare for those accordingly, only now will the parsing be a solution. But you are not likely going to be able to parse your way out of failures you have no idea are possible.

**Comment by QuantumLlama** [comment]
I think it would be helpful to update the API endpoints with possible `status` it could output, and provide documentation for all `status` codes.

Here are the error codes used, almost all should match an OPSkins Error Code, which have descriptions [here](https://docs.opskins.com/public/en.html#headers).

1xx user account errors
2xx internal errors
3xx user error
4xx third party error

JS Object:
```javascript
const ErrorCodes = {
  OK: 1,

  GENERIC_USER_ACCOUNT_ERROR: 102,
  ACCESS_DENIED: 106,
  NOT_LOGGED_IN: 108,
  NEEDS_TWOFACTOR: 112,
  TWOFACTOR_INCORRECT: 122,
  USERNAME_TAKEN: 124,
  UNACCEPTABLE_USERNAME: 126,

  GENERIC_INTERNAL_ERROR: 202,
  DATABASE_ERROR: 204,
  NOT_FOUND: 206,
  BAD_STATE: 208,
  NO_MATCHING_ITEMS_FOUND: 210,
  CANNOT_CREATE_DIRECTORY: 216,
  FILE_UPLOAD_ERROR: 218,
  FILE_UPLOAD_ALREADY_EXISTS: 220,
  CANNOT_DELETE_FILE: 222,
  ALREADY_IN_THAT_STATE: 226,
  LOCKED: 228,
  DISABLED: 234,
  MALFORMED_RESPONSE: 236,
  EXPIRED: 238,
  EMPTY_DATA: 240,
  ITEM_NEEDS_REPAIR: 246,
  ITEM_NOT_IN_INVENTORY: 248,

  BAD_INPUT: 302,
  UNACCEPTABLE_ITEM: 304,
  DUPLICATE_ITEM: 306,
  BAD_REQUEST: 312,
  CAPTCHA_INVALID: 316,
  RATE_LIMIT_EXCEEDED: 318,
  MISSING_DEPENDENCY: 326,
  REQUEST_OR_FILE_TOO_LARGE: 330,
  UNACCEPTABLE_FILE_TYPE: 332,

  THIRD_PARTY_UNAVAILABLE: 408
}
```

PHP Array
```php
$errorCodes = [
    "OK" => 1,
    
    "GENERIC_USER_ACCOUNT_ERROR" => 102,
    "ACCESS_DENIED" => 106,
    "NOT_LOGGED_IN" => 108,
    "NEEDS_TWOFACTOR" => 112,
    "TWOFACTOR_INCORRECT" => 122,
    "USERNAME_TAKEN" => 124,
    "UNACCEPTABLE_USERNAME" => 126,
    
    "GENERIC_INTERNAL_ERROR" => 202,
    "DATABASE_ERROR" => 204,
    "NOT_FOUND" => 206,
    "BAD_STATE" => 208,
    "NO_MATCHING_ITEMS_FOUND" => 210,
    "CANNOT_CREATE_DIRECTORY" => 216,
    "FILE_UPLOAD_ERROR" => 218,
    "FILE_UPLOAD_ALREADY_EXISTS" => 220,
    "CANNOT_DELETE_FILE" => 222,
    "ALREADY_IN_THAT_STATE" => 226,
    "LOCKED" => 228,
    "DISABLED" => 234,
    "MALFORMED_RESPONSE" => 236,
    "EXPIRED" => 238,
    "EMPTY_DATA" => 240,
    "ITEM_NEEDS_REPAIR" => 246,
    "ITEM_NOT_IN_INVENTORY" => 248,
    
    "BAD_INPUT" => 302,
    "UNACCEPTABLE_ITEM" => 304,
    "DUPLICATE_ITEM" => 306,
    "BAD_REQUEST" => 312,
    "CAPTCHA_INVALID" => 316,
    "RATE_LIMIT_EXCEEDED" => 318,
    "MISSING_DEPENDENCY" => 326,
    "REQUEST_OR_FILE_TOO_LARGE" => 330,
    "UNACCEPTABLE_FILE_TYPE" => 332,
    
    "THIRD_PARTY_UNAVAILABLE" => 408
];
```

PHP consts:
```php
    const OK = 1; // no error

    // 1xx = user account error
    const GENERIC_USER_ACCOUNT_ERROR = 102;
    const ACCESS_DENIED = 106;
    const NOT_LOGGED_IN = 108;
    const NEEDS_TWOFACTOR = 112;
    const TWOFACTOR_INCORRECT = 122;
    const USERNAME_TAKEN = 124;
    const UNACCEPTABLE_USERNAME = 126;

    // 2xx = internal error
    const GENERIC_INTERNAL_ERROR = 202;
    const DATABASE_ERROR = 204;
    const NOT_FOUND = 206;
    const BAD_STATE = 208;
    const NO_MATCHING_ITEMS_FOUND = 210;
    const CANNOT_CREATE_DIRECTORY = 216;
    const FILE_UPLOAD_ERROR = 218;
    const FILE_UPLOAD_ALREADY_EXISTS = 220;
    const CANNOT_DELETE_FILE = 222;
    const ALREADY_IN_THAT_STATE = 226;
    const LOCKED = 228;
    const DISABLED = 234;
    const MALFORMED_RESPONSE = 236;
    const EXPIRED = 238;
    const EMPTY_DATA = 240;
    const ITEM_NEEDS_REPAIR = 246;
    const ITEM_NOT_IN_INVENTORY = 248;

    // 3xx = user error
    const BAD_INPUT = 302;
    const UNACCEPTABLE_ITEM = 304;
    const DUPLICATE_ITEM = 306;
    const BAD_REQUEST = 312;
    const CAPTCHA_INVALID = 316;
    const RATE_LIMIT_EXCEEDED = 318;
    const MISSING_DEPENDENCY = 326;
    const REQUEST_OR_FILE_TOO_LARGE = 330;
    const UNACCEPTABLE_FILE_TYPE = 332;

    // 4xx = Third party error
    const THIRD_PARTY_UNAVAILABLE = 408;
```

**Comment by rannmann** [comment]
Added an internal ticket to go back and fix all the instances where HTTP status codes are the error code in the API response.

**Comment by rannmann** [comment]
Error codes have been updated for API endpoints so they no longer show the HTTP Status code as the error code.
