### ISSUE TITLE
wear_tier_index filter not working

### ISSUE THREAD

**Issue by steamanalyst** [OPSkins/trade-opskins-api#21]
Example:

Multiple SKU: GetItems/v1?key=apikey&sku_filter=100,102&wear_tier_index=1

wear_tier_index has no effect.

**Comment by QuantumLlama** [comment]
It does for me

https://api-trade.opskins.com/IItem/GetItems/v1?key=apikey&sku_filter=100,102

https://api-trade.opskins.com/IItem/GetItems/v1?key=apikey&sku_filter=100,102&wear_tier_index=1
