### ISSUE TITLE
Something wrong with 'GetUserInventoryFromSteamId'

### ISSUE THREAD

**Issue by kasian-ll** [OPSkins/trade-opskins-api#22]
This request https://api-trade.opskins.com/ITrade/GetUserInventory/v1/?uid=1&app_id=1 gives user with steamid 76561197973578969, but this gives https://api-trade.opskins.com/ITrade/GetUserInventoryFromSteamId/v1/?steam_id=76561197973578969&app_id=1 
404 ERROR.I'm doing something wrong or it's a bug ?

**Comment by Tinboy** [comment]
Yep,that was the problem.But why api sent me 404 instead of 401 or 400?

**Comment by rannmann** [comment]
It's not found for that *type* of request.  We've been working on improving those HTTP errors over the past few days.  I'll add this one to my list.

**Comment by b3none** [comment]
Yeah definitely return a `401` please.
