### ISSUE TITLE
How to get the 2fa secret key

### ISSUE THREAD

**Issue by wedzyou** [OPSkins/trade-opskins-api#26]
Hi i'm currently try to document me on the api and i see for some request we need a 2fa secret code and i was asking the question how to get it ? Is it like on steam with the shared_secret and the identity_secret or it's totaly different ?
if someone can help me that would be nice.

Have a nice day

**Comment by QuantumLlama** [comment]
Hello,

Please see: https://github.com/OPSkins/trade-opskins-api/issues/16

**Comment by QuantumLlama** [comment]
Lets keep this issue open until I update docs with a guide for this, thanks.

**Comment by wedzyou** [comment]
Ok nice thanks for the answer sorry i didn't see the issue was already ask. 

Have a nice day.
