### ISSUE TITLE
HTML error pages being returned from the api

### ISSUE THREAD

**Issue by ha1331** [OPSkins/trade-opskins-api#29]
How am I supposed to deal with a response that is an html-page?  I had to go in, print the "error" to the console, copy paste it to a text file to see what the error was. Does not seem like something one would expect to get from an api. At the same time other sites that I tested seemed to work fine and now mine works fine too. Wasn't doing anything super experimental either, just getting the users key count, that one user that was me, the only user ever visited the site on my localhost. 

https://gyazo.com/b8af3714131a1bed4764e8ffdeaa430a

**Comment by QuantumLlama** [comment]
I believe ICaseSite interface was unavailable for a short period. It would have returned a proper JSON response, so it's likely the page you saw is the behavior of a browser extension, some other program on your computer, or DNS provider.

**Comment by ha1331** [comment]
Browser extension? I doubt it, because I'm not aware of any extension that is able to hijack traffic outside of the browser and if one existed, it surely would not be a good thing. I also have never seen shit page on actual browser and I'm pretty sure I have hit a website that wasn't reachable prior to this. Anyways, this seems to have been a one time event that happened at the same time these items migrated to  the wax chain.

**Comment by memiamap** [comment]
I've also seen this at times.  The HTML is from Cloudflare and is about the destination site being unavailable.  Can't remember the exact HTTP status code (maybe 554?).

**Comment by rannmann** [comment]
Yeah, this was a one-time thing.
