### ISSUE TITLE
Cloudflare is blocking requests

### ISSUE THREAD

**Issue by SzymonLisowiec** [OPSkins/trade-opskins-api#3]
403 Forbidden on `/ITest/Test/v1/`

**Comment by rannmann** [comment]
Are you sure you're hitting the correct URL?

https://api-trade.opskins.com/ITest/Test/v1 is working for me.

**Comment by SzymonLisowiec** [comment]
Yes, That is strange. I tested it on the request library, Postman and my browser, only on the request library not working. But if I tried https://api.opskins.com/ITest/Test/v1/ , it work on all.

**Comment by rannmann** [comment]
Happy to hear it's working for you now!
