### ISSUE TITLE
feature suggestion: webhooks

### ISSUE THREAD

**Issue by ha1331** [OPSkins/trade-opskins-api#30]
Consider adding webhooks, it would simplify the implementation of bots and would reduce the strain on your end when people don't need to poll the trades. to catch changes. I know this is very compact  explanation and justification of the merits of the feature, but I feel it's enough to make the case for the usefulness.

**Comment by makcc666** [comment]
This is the thing that was missing in STEAM (about this pain)

**Comment by TheTimmaeh** [comment]
Already upvoted, though I want to point out once again that this would reduce the load onto the API a lot. Highly anticipated.

**Comment by rannmann** [comment]
If you had to choose between webhooks and a websocket you could connect to, which would you prefer?

**Comment by DylanGoodman** [comment]
Webhooks please sir.

**Comment by TheTimmaeh** [comment]
I'm relying on sockets for my application, but either is fine I guess. Webhooks would require an accessible webserver though, which could be harder to implement on local environments.

**Comment by ha1331** [comment]
@TheTimmaeh if your connection between the user and your backend relies on sockets, I'm not sure how you would be able to integrate the sockets between opskins and your backend to the user facing aspect of the application. Just in case there's some kind of confusion,  the users are not supposed to connect to the opskins api with this method. Your backend would and then you would propagate these actions to the user.

**Comment by ha1331** [comment]
@TheTimmaeh as to local environments, I don't think that should be that big of a deal. What you would get as payload would likely be same thing you now request from the api. It should be fairly trivial to test and implement that functionality without ever interacting with opSkins. After all you would be dealing with http(s)-requests that you could initiate your self and it would make no difference to your application.

**Comment by feed4rz** [comment]
I think you should be able to choose between webhooks and websockets depending on your needs.

**Comment by feed4rz** [comment]
Any progress guys?

**Comment by makcc666** [comment]
I hope if the project works again, we will see the opportunity to receive notifications via WebHooks
