### ISSUE TITLE
feature suggestion: user defined expiration

### ISSUE THREAD

**Issue by ha1331** [OPSkins/trade-opskins-api#33]
Currently the trades expire in 2 weeks. I'm sure it's enough for slightly slower person to accept it, but I would be willing to bet 99% percentile is somewhere around a day. Instead of making the default smaller, perhaps make it possible to define how long the trade should be valid.

**Comment by QuantumLlama** [comment]
Interesting suggestion.

For now, you could add a system to cancel the trade offers after a certain period.

**Comment by QuantumLlama** [comment]
Added to `ITrade/SendOffer` & `ITrade/SendOfferToSteamId`

Thanks!

**Comment by QuantumLlama** [comment]
Correction 2: We added it as a unix timestamp, will be changing it soon to seconds for simplicity. Avoid using the input for now.

**Comment by QuantumLlama** [comment]
Added `expiration_time` input about 2 weeks ago.

Thanks!
