### ISSUE TITLE
feature request:  /ICaseSite/GetTradeStatus/v1 make it possible to fetch multiple trades in one request

### ISSUE THREAD

**Issue by ha1331** [OPSkins/trade-opskins-api#39]
This endpoint and thinking behind it, is very confusing to me. 
Unlike `/ITrade/GetOffers/v1/` that allows a parameter `ids` to be a comma separated list of id's, this one is one trade per request. You're basically forcing us to spam your api.

Here's some math to consider:
If you assume there's a site that will have on average 10 active case opening at any given time. Let's assume on average users will accept the trade in one minute. If you poll every 5 seconds, that means it's 12 calls to your api per case opening, 120 calls every minute. in hour that's  7.2k calls, in a day 172k calls. Compared to 12 * 60 * 24 = 17280 if this was same as `/ITrade/GetOffers/v1/` . There's a difference of 155k call a day.

Now that it seems that this is the only way to get the trade statuses, are these endpoints ratelimited or am I supposed to hammer it like there's no tomorrow? If there is a  rate limit, what is it?

As a sidenote, this one is more about me just being curious... these trades have a property called `state_name` . Now if I just send a trade and the user has not done anything to it, this state_name is `open`. So, when a person is opening a case and they have not done anything, they are expected to accept (or decline) the trade, at this point the state is `open`? If I show this to a user, what exactly are they supposed to understand? If this is not meant to be used in a user facing context, what is the logic? That must be the worst word to choose out of all the "waiting", "pending", "sent" or similar and you actually chose the most confusing one?

**Comment by TheTimmaeh** [comment]
I second this. Though I'd actually appreciate an open method of getting all case openings, a simple copy of GetOffers, though accessible via a VCaseUser. Alternatively the existing endpoint could listen to calls made by a VCaseUser and return those offers instead of an error.

Yet a socket or webhook solution would be more appreciated.

**Comment by ha1331** [comment]
@TheTimmaeh #30 if you wan't to share your opinion about webhooks

**Comment by rannmann** [comment]
I think this was a case of one API endpoint getting added features and the other getting left in the dust.  Adding multiple offer id inputs to that endpoint seems reasonable.  I've created a ticket on our end for this functionality to get added.

To answer your second question: The only rate-limiting is imposed by cloudflare.  I don't remember what limits they impose off-hand.

The state name refers to the state of the trade offer.  It should be one of: Open, Accepted, Expired, Cancelled, Declined, Invalid Items, Pending Case Opening, or Expired Case Opening.  The latter two *only* apply to VCase site trade offers.
