### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by SzymonLisowiec** [OPSkins/trade-opskins-api#4]
Sometimes (once on a few requests) server responding 
> 500 Internal Server Error

**Comment by rannmann** [comment]
Can you provide more details?  Is this happening as a first request, intermittently, to certain API endpoints only?

**Comment by SzymonLisowiec** [comment]
For sure in `/ITest/Test/v1/` and maybe in another endpoints. I can't specify frequency.

# Request's Details (from Google Chrome devtools)
## Generals
**Request URL**: https://api-trade.opskins.com/ITest/Test/v1/
**Request Method**: GET
**Status Code**: 200 
**Remote Address**: 104.16.55.80:443
**Referrer Policy**: no-referrer-when-downgrade

## Response
500 Internal Server Error

## Response Headers
**access-control-allow-origin**: *
**cache-control**: no-cache
**cf-railgun**: ad1ce410de stream 0.000000 0210 e6be
**cf-ray**: 42715c2f6ae02af7-WAW
**content-length**: 25
**content-type**: application/json
**date**: Thu, 07 Jun 2018 07:21:08 GMT
**expect-ct**: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
**expires**: Wed, 21 Oct 2015 07:28:00 GMT
**pragma**: no-cache
**server**: cloudflare
**status**: 500
**vary**: Accept-Encoding
**x-powered-by**: HHVM/3.26.2

## Request Headers
**:authority**: api-trade.opskins.com
**:method**: GET
**:path**: /ITest/Test/v1/
**:scheme**: https
**accept**: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
**accept-encoding**: gzip, deflate, br
**accept-language**: pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7
**cache-control**: max-age=0
**cookie**: _hidden_
**upgrade-insecure-requests**: 1
**user-agent**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

**Comment by rannmann** [comment]
Reproduced.  Investigating.

**Comment by rannmann** [comment]
This error was incredibly hard to test, so I'm not positive it's fixed.  A deploy went out a few minutes ago that should have resolved it though.   Let me know if you run into it again.

**Comment by SzymonLisowiec** [comment]
Seems it works without problems. :D
