### ISSUE TITLE
Functionality request in ITrade/GetOffers - Search by trade age

### ISSUE THREAD

**Issue by memiamap** [OPSkins/trade-opskins-api#46]
I would like to request a parameter be added to `ITrade/GetOffers` that allows you to specify that you only want to receive trades that were created within a certain length of time (before now).

### How would it work?
For example:

`GET https://api-trade.opskins.com/ITrade/GetOffers/v1/?trade_age=600`

The `trade_age` (or whatever you want to call it) would cause the `GetOffers` call to return only trades that had been created within the last 600 seconds.

### Why do this?
I have a site where we handle many trades taking place over the course of a day.

It does not make sense to use the `ids` parameter to filter out trades that the bot does not want, because there could be hundreds\thousands of them.

Instead, I would prefer to handle only trades that are relevant to the bot currently.  All trades on the site are cancelled within a few minutes if not actioned;  A time-based filter would allow our bots to significantly reduce the number of trades that they have to 'process' that are actually redundant and never going to be resurrected.

**Comment by jtquant** [comment]
@memiamap I like the suggestion. Also, how are you setting the expiration time of a trade offer? I thought the expiration date was just a default value, and was not able to be set.
