### ISSUE TITLE
Allow vcase user to use GetOffer/GetOffers endpoints

### ISSUE THREAD

**Issue by waylaidwanderer** [OPSkins/trade-opskins-api#56]

**Comment by SzymonLisowiec** [comment]
Duplicate of #39

**Comment by waylaidwanderer** [comment]
Not really, it's a different request. A Trade Offer object has different data compared to `ICaseSite/GetTradeStatus`.

**Comment by jor112358** [comment]
Yes, I need this too, so I can get the case opening history.
