### ISSUE TITLE
How to get odds of case Items?

### ISSUE THREAD

**Issue by Marow** [OPSkins/trade-opskins-api#57]
LootVGO show Percentage / Odds of each Item in a VGO Case.

Where they get it? Doesnt find that in ICase/GetCaseSchema or IItem/GetItems

**Comment by Marow** [comment]
Any ideas/updates? Where they get the odds from the items in cases

**Comment by rannmann** [comment]
https://docs.google.com/spreadsheets/d/1PF1LAFAzHvc2KP_GaZXkNN18adNwNBvatDa1Jrr5KbI/edit#gid=248650649

We will add this data to the API at some point.

**Comment by Marow** [comment]
Nice lets wait for that on API :) 👍

**Comment by ha1331** [comment]
@rannmann Could you update the case odds doc to contain the newest case too? Kind of need these so that my thing is able to show the same data for all the cases

**Comment by ha1331** [comment]
@QuantumLlama  how about you? Anyone? Any chance of getting that sheet updated?

**Comment by ha1331** [comment]
any chance you could add those odds for the new case? If not, could someone say it's not happening for what ever reason, so at least I know? I'm sure you are all very busy doing your things, so I'm not asking for the pleasure of nagging, not feeling like I'm entitled for some special treatment including but not limited to massages. Would just like to get these and I assume so would other people.

**Comment by ha1331** [comment]
Thank you, who ever added the odds to the sheet. Much appreciated.

**Comment by Marow** [comment]
Thats odds never real... the Legendary on Case 2 is lower than 3 and 4? But the 3 and 4 worth more? 
Looks not really real.

Waiting for add odds to api

**Comment by QuantumLlama** [comment]
Hello,

Added case odds endpoint: https://github.com/OPSkins/trade-opskins-api/blob/master/ICase/GetCaseOdds.md

Thanks!
