### ISSUE TITLE
Invalid Items on Accepted Trade?

### ISSUE THREAD

**Issue by Marow** [OPSkins/trade-opskins-api#59]
Hi,

`https://api-trade.opskins.com/ICaseSite/GetTradeStatus/v1`
Send me `state: 8` with state_name `'Invalid Items'` but it was accepted.

Thats is now the 2nd or 3rd time that this comes.

Why is that?
In my Code check the offer some times, first i get state 2, "Open" than i accepted it and get state 8.

Any bug there or something?

**Comment by QuantumLlama** [comment]
Hello,

A fix was deployed for this (Thursday evening). Is this still an issue?

**Comment by ha1331** [comment]
happened 7 hours ago last time I noticed it.

**Comment by Marow** [comment]
Happend today, i let them run for some times and when more than 10 times invalid than i kick that out

**Comment by QuantumLlama** [comment]
Looks like we only fixed this issue for normal trade offers. Case site trade offers act a little differently. Will fix this issue as soon as possible.

Thanks

**Comment by rannmann** [comment]
Issue fix deployed for case site endpoint.  Can you confirm that it's fixed?

**Comment by Marow** [comment]
Thats not fixed

**Comment by QuantumLlama** [comment]
@Marow What state does it change from?

Current known issue is offers can go from Expired to Invalid, this should be fixed early next week.

**Comment by SmileFX** [comment]
@QuantumLlama For me it goes from Pending to Invalid after acceptance. And it still does, today it wouldnt even let me do anything for a good 1h because EVERY offer went to Invalid Items

**Comment by QuantumLlama** [comment]
@SmileFX Thank you very much for the info, please keep me updated with any more strange cases. I am actively investigating this issue and will push some fixes early next week.

**Comment by QuantumLlama** [comment]
@SmileFX 

Hello,

We pushed an update few minutes ago to help resolve issues with offers going from a permanent state (e.g. invalid) to another permanent state (e.g. accepted). We would appreciate any further feedback regarding this.

Thanks
