### ISSUE TITLE
SendOffer returns error, but the offer is actually sent?

### ISSUE THREAD

**Issue by ghost** [OPSkins/trade-opskins-api#61]
I'm really confused, the error returns empty object. But when i check the offer history the offer is actually sent okay.

Code:
```
let options = {
    method: 'POST',
    uri: 'https://api-trade.opskins.com/ITrade/SendOffer/v1/',
    body: {
    	key: 'myAPIKey',
        twofactor_code: 2faCode,
        uid: uid,
        token: token,
        items: items
    },
    json: true
};

rp(options)
    .then(function (parsedBody) {
        // POST succeeded...
    })
    .catch(function (err) {
        // POST failed...
    });
```

**Comment by ha1331** [comment]
I suggest you include the actual error in this.  I bet it's cloudflare returning what ever it is, that is not at all json. I got this too. It helped when I manually set browser header like so:

```
headers   : {
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"
        }
```

**Comment by siriate** [comment]
I put the header and it now gives normal response, thanks 👍

**Comment by rannmann** [comment]
What you're doing shouldn't be required.  We'll audit our cloudflare rules and see if we can fix it.  Thanks for letting us know!
