### ISSUE TITLE
allow ICaseSite to generate the items in a different steamid

### ISSUE THREAD

**Issue by austinnguyen01** [OPSkins/trade-opskins-api#63]
like unbox cases using our keys to make the items on someone else account using their id

**Comment by ha1331** [comment]
I don't think you need anything new for this. You are free to open cases with any account you choose to use. You just need the keys (perhaps the user deposits these keys), a caseBot to send this "keyBot"  account a trade, you make this keyBot account accept that trade and you have now effectively opened cases "for someone else". It's then upto you to "connect" these case openings with the person "you opened for".  I might assume something that's not in place here, but in that case I suggest you provide more information about your particular usecase.
