### ISSUE TITLE
Can you share skins images in resolution 1200x1200?

### ISSUE THREAD

**Issue by SzymonLisowiec** [OPSkins/trade-opskins-api#64]
We have curious feature on our website, but images is too small.

**Comment by austinnguyen01** [comment]
for now you can just scale them up won't be as "hd" but it should work

**Comment by rannmann** [comment]
For individual items, the full images are 2560x1440: https://files.opskins.media/file/vgo-img/previews/493309_front.jpg

**Comment by SzymonLisowiec** [comment]
@rannmann but I need with transparent background :/

**Comment by QuantumLlama** [comment]
Hello,

This is in the works.

Thanks

**Comment by QuantumLlama** [comment]
Hello, we added resolutions 900px 1800px 2500px to the [Standard Item Object](https://github.com/OPSkins/trade-opskins-api/blob/master/IItem.md#standard-item-object)

Thank you!
