### ISSUE TITLE
Cases array is not fully populated when checking accepted offers

### ISSUE THREAD

**Issue by tacyarg** [OPSkins/trade-opskins-api#67]
When checking an accepted offer using `ICaseSite/GetTradeStatus/v1` the cases array returned is not populated properly for some time.

**Comment by rannmann** [comment]
If you can show me a response where the state is actually 3 and there are no cases, I'll open an internal ticket.  But I think this is related to #59 where the offer goes into INVALID_ITEMS temporarily (which should be fixed now).

Let me know if you encounter this again.
