### ISSUE TITLE
404 from OpenWithKeys doesnt explain whats missing

### ISSUE THREAD

**Issue by atmd83** [OPSkins/trade-opskins-api#68]
hitting `https://api-trade.opskins.com/ICase/OpenWithKeys/v1` is returning a 404 but doesnt explain whats actually missing

the url is correct as sending a GET requests return an error saying it needs to be a POST, so is the 404 refering to a key? (i.e. the key the user account must have?)

**Comment by ha1331** [comment]
@atmd83  why would you assume it should work with GET? It says on the documentation  the request is POST, the api is telling you the same thing. Also according to the documentation you are supposed to provide api key. You are also required to provide parameter case_id, and if you want to open more than one case, you're supposed to provide a parameter amount, that defaults to 1.

Am I missing something here? If so, I suggest you provide more information, such as what you are actually doing that is failing.

**Comment by atmd83** [comment]
sorry yes I should have given more details

you're right that it needs to be a POST request, but when I got the 404 I tried a GET, the error from that would suggest the url wasnt a 404 and that the 404 was resourse missing rather than the url

I sent with it the case id, number of cases to open and my api key
api key works on all other requests so assumed the api key wasnt the issue

so for the full info

url: POST https://api-trade.opskins.com/ICase/OpenWithKeys/v1
sending key, case_id & amount values
(I tried is as url params, headers and json body

returned 404, mesage "not found"

**Comment by atmd83** [comment]
@ha1331 the idea is to do a csse site, currently though just exploring the api so I understand it better

**Comment by ha1331** [comment]
@atmd83 very interesting, this is indeed a weird one. Tho if you're not extremely creative, I doubt you will find use for this endpoint. The ones you want to get familiar with are:

https://github.com/OPSkins/trade-opskins-api/blob/master/IUser/CreateVCaseUser.md to create the case opening account

https://github.com/OPSkins/trade-opskins-api/tree/master/ICaseSite to get the key counts, send case opening trades and keeping track of their state(s)

**Comment by QuantumLlama** [comment]
This endpoint has been disabled until further notice.
