### ISSUE TITLE
Getting wrong trade state

### ISSUE THREAD

**Issue by tuz1k** [OPSkins/trade-opskins-api#72]
I'm sending trade to steamid and console logging response.offer.state every second but nothing is changing even when user accepts the trade, how do I suppose to get the state of the trade?

**Comment by ha1331** [comment]
@tuz1k I'm not sure what you mean, but you're supposed to use  https://github.com/OPSkins/trade-opskins-api/blob/master/ITrade/GetOffers.md to query the offer(s) state(s).

**Comment by ha1331** [comment]
Relevant issues you might want to keep an eye for: #30  and  #33
