### ISSUE TITLE
Standard User Public Profile Object should include `id` and `steam_id` too

### ISSUE THREAD

**Issue by waylaidwanderer** [OPSkins/trade-opskins-api#76]
Title. SteamID on Steam has always been a public identifier, and I see no reason why the OPSkins UID and SteamID shouldn't be present in the [Standard User Public Profile Object](https://github.com/OPSkins/trade-opskins-api/blob/master/IUser.md#standard-user-public-profile-object).

This would be useful for converting a SteamID to OPSkins UID, as you could just make a call to `/ITrade/GetUserInventoryFromSteamId/v1/` with a SteamID and grab the OPSkins UID from the `user_data` response.

**Comment by QuantumLlama** [comment]
Added!

Thanks
