### ISSUE TITLE
Will there be something to validate winnings?

### ISSUE THREAD

**Issue by DylanGoodman** [OPSkins/trade-opskins-api#78]
As title says, I don't see anything about this. Is there anything out that a person can confirm winnings or use a trade id?

**Comment by ha1331** [comment]
the person "doesn't need to" confirm anything. When the case opening is done, the user will receive the items they receive. The case opening site doesn't have any way to affect the outcome of the case opening. That's as far as "provably fair" goes currently. 

All you can honestly say is, your site is not able to affect the outcome. At the end of the day it boils down to trusting opskins to not scam. The "provably fair" used to be "you can look at the smart contract" but that has long passed when opskins now doesn't utilize the ethereum chain, but their fork of what ever chain they are utilizing and calling WAX (I think eos). Now it could be that one day that blockchain will become public and there might be a way to see these case openings recorded in that chain, but that's few buts and ifs included and I'm not sure that constitutes as provably fair anyways.
