### ISSUE TITLE
Commission payouts for Case Site

### ISSUE THREAD

**Issue by MikeMcKn** [OPSkins/trade-opskins-api#80]
Hello,

I would like know how affiliate commission is paid after case opening through SendKeyRequest method is used. I tried to open few cases with sending eth address in format `0x111111....` and few cases on different account after using UpdateCommissionSettings to set OpSkins account. 

In the first case no commission in ETH has been paid (it's been around 24h since my try), in case when OpSkins was set, commission was paid almost instantly. 

How does it suppose to work? How and if eth commissions are paid when no OpSkins account is set?

**Comment by QuantumLlama** [comment]
Hello,

We used to pay with ETH before but completely switched over to OPSkins USD Wallets. All commission is saved and distributed when you link your OPSkins account through ICaseSite/UpdateCommissionSettings.

We will soon remove the `affiliate_eth_address` input from SendKeyRequest

Thanks
