### ISSUE TITLE
Empty items array in response after creating trade

### ISSUE THREAD

**Issue by lelek16** [OPSkins/trade-opskins-api#86]
Hi, i've just noticed, that in response after create trade (/ITrade/SendOffer/v1/) arrays of items are empty in sender and recipient objects. But when i'm fetching offer details (ITrade/GetOffer/v1) - everything looks ok.

Is this normal?

**Comment by QuantumLlama** [comment]
Hello,

This is a known bug. We are looking into it.

Thanks

**Comment by QuantumLlama** [comment]
Hopefully fixed now. Let me know otherwise, thanks.
