### ISSUE TITLE
404 Not Found error: Get Inventory from steam id

### ISSUE THREAD

**Issue by PatchDevel** [OPSkins/trade-opskins-api#88]
Hello

https://api-trade.opskins.com/ITrade/GetUserInventoryFromSteamId/v1?steam_id=<steam_id>&app_id=1

I use this api for get items
But it shows 404 error
{
    "status": 404,
    "time": 1537509118,
    "message": "Not Found"
}

How can I resolove this?

**Comment by ha1331** [comment]
It means the user doesn't have opskins account.  Also it's likely you wouldn't want to get app_id=1

**Comment by QuantumLlama** [comment]
Hello,

If the user does not exist, the message will say "No such user found".

However, I believe what you need to do is send an API Key, as this endpoint requires it. `&key=yourapikey`

Thanks
