### ISSUE TITLE
Duplicate item IDs are ignored

### ISSUE THREAD

**Issue by almatrass** [OPSkins/trade-opskins-api#89]
Not really a bug with the API, however duplicate item IDs in trades are ignored.

It's an issue that really should be dealt with by us before sending, but wouldn't it be more sensible to just abort trade if there are dupes on your end? Since if there are duplicates, an error has almost certainly occurred on our end.

**Comment by QuantumLlama** [comment]
Hello,

We will be adding this sanity check when we add the feature to send Item IDs separately, like so: 
`items_to_send`  & `items_to_receive`

Thanks for bringing this up.

**Comment by QuantumLlama** [comment]
Added `items_to_send` & `items_to_receive` inputs in `SendOffer` endpoints which check for same Item IDs.

Thanks
