### ISSUE TITLE
OAuth redirect url

### ISSUE THREAD

**Issue by NeptunApps** [OPSkins/trade-opskins-api#92]
I set redirect URL for OAuth - `waxtradeclient://auth`
But OPSkins is redirecting to `https://opskins.com/waxtradeclient://auth/?state=1234567&code=CODE#`
As result 404 error.

Don't get confused by my URL, that's for Android app

**Comment by QuantumLlama** [comment]
Hello,
This should be fixed now
Thanks

**Comment by NeptunApps** [comment]
No, same stuff

**Comment by QuantumLlama** [comment]
@NeptunApps  Sorry about that, can you please try now?
Thanks
