### ISSUE TITLE
IItem 3d_viewer Invalid Syntax on NodeJS

### ISSUE THREAD

**Issue by Marow** [OPSkins/trade-opskins-api#94]
NodeJS cannot handle with numbers on variables like that.

Please change the 3d_viewer in https://github.com/OPSkins/trade-opskins-api/blob/master/IItem.md to another name without numbers on it.

Otherwise its not that easy to handle like every other variables like video or something.
Please change to live_viewer or something and not with a Number.

**Comment by ha1331** [comment]
what do you mean? What are the limitations of numbers in variables, in node?

**Comment by ha1331** [comment]
This is totally doable in node:
```
let videoForMarow = standardItemObject.preview_urls["3d_viewer"];
```

**Comment by Marow** [comment]
With that i get "null" back... not the 3d_viewer...

Thats what i use for video
`item.preview_urls.video`

that works, but if i change video to 3d_viewer it doesnt work
