### ISSUE TITLE
What limitations apply to user name?

### ISSUE THREAD

**Issue by NeptunApps** [OPSkins/trade-opskins-api#96]
Method `IUser/UpdateProfile`, what limitations apply to `display_name`?

And is there a way to change user avatar?

**Comment by QuantumLlama** [comment]
Hello,

Currently no way to change user avatar, but it's planned.

`display_name` can be max `32` characters and has certain offensive word restrictions along with these:

```
admin
administrator
moderator
staff
```

Thanks!
