### ISSUE TITLE
Is there a way to validate trade link?

### ISSUE THREAD

**Issue by NanoEdit** [OPSkins/trade-opskins-api#97]
I want to validate trade link before sending trade offer.
Because token in trade URL could be invalid or regenerated.

**Comment by QuantumLlama** [comment]
Hello,

It's not possible to programmatically verify that the token is valid.

However, you may call `ITrade/SendOffer` with only API key + `twofactor_code` + `trade_url`, and it will give an error like this:

```json
{
    "status": 302,
    "time": 1539474037,
    "message": "Invalid trade_url"
}
```

Thanks!
