### ISSUE TITLE
How does the Authentication for SendOffer & AcceptOffer endpoints work?

### ISSUE THREAD

**Issue by 7ukasz** [OPSkins/trade-opskins-api#98]
When I put my API key (with or without secret) base64 encoded in the header and try to send an offer through the SendOffer endpoint it works when I'am doing it with the account associated with that API key (after providing the 2FA for that account).

When I try to use the SendOffer with an other user I get a 122 after providing 2FA associated with the sending account (not the API key account). This makes sense since I didn't specify the sending user in the request (although it could be derived from the item id). So is the send & accept only possible with the users API Key? Or how do use the API without going through OPSkins (oAuth)?

**Comment by feed4rz** [comment]
apikey shouldnt be encoded or passed through some header. You can just pass it as a query parameter:

‘’’
SendOffer/?key=YOUR_APIKEY
‘’’

**Comment by DylanGoodman** [comment]
You don't send the api key, just the Bearer Token.

**Comment by 7ukasz** [comment]
Yeah, in case you use oAuth through OPSkins. I was asking for a possibility to use the API without authenticate on a specific marketplace. But maybe this will be possible when WAX Blockchain 😉 gets released.

**Comment by Nisthar** [comment]
@DylanGoodman can you show me an example how to send it? Do i need to convert it into base64?
